### PR TITLE
Fix duplicated bundle resource processing

### PR DESCRIPTION
**Pull request by diorcety**
In my project i have heavy processing of less files (30 seconds to process). I noticed that the processing of the bundle are done twice. This fix allow to have only one processing and for my case to divide almost by 2 the processing time.

### CODE REVIEW

**Comment by ic3fox** [comment]
Hi,

I'll take a look at it.
The JIRA [JAWR-381](https://java.net/jira/browse/JAWR-381) has been created to follow this issue.

Cheers,

**Comment by ic3fox** [comment]
Hi,

With the modification of the ResourceBundlesHandlerImpl class, it seems not enough to fix the duplicate processing.
Am I missing something?
I'm thinking about putting a cache on the generated content to fix this.

**Comment by diorcety** [comment]
Strange, maybe that fix not all the duplicate stuff, but it fixes the most time consuming for me.

**Comment by ic3fox** [comment]
Hi,

This issue has been fixed in the 3.9 version.
Thanks for the pull request

**Pull request closed without merging**
